//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imc.Application.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imc.Application.Resourses.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É importante garantir uma dieta equilibrada e nutritiva.
        ///Consulte um profissional de saúde para orientação personalizada
        ///e alcance seu peso ideal.
        ///Sua saúde é nossa prioridade!.
        /// </summary>
        internal static string Magreza {
            get {
                return ResourceManager.GetString("Magreza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parabéns! Você está no peso ideal!
        ///Continue assim e mantenha esse estilo de vida saudável.
        ///Sua dedicação é incrível!.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vamos trabalhar juntos para alcançar um peso saudável!
        ///Consulte um nutricionista e adote hábitos alimentares
        ///e de exercício físico.
        ///Sua jornada para uma vida mais saudável começa agora!.
        /// </summary>
        internal static string Obesidade {
            get {
                return ResourceManager.GetString("Obesidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorize sua saúde!
        ///Considere procurar a orientação de um médico e nutricionista 
        ///para criar um plano personalizado.
        ///Estamos aqui para apoiar você em sua jornada.
        ///Pequenos passos levam a grandes mudanças!.
        /// </summary>
        internal static string ObesidadeGrave {
            get {
                return ResourceManager.GetString("ObesidadeGrave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estamos quase lá!
        ///Faça alguns ajustes em sua rotina diária,
        ///focando em escolhas alimentares mais saudáveis e atividades físicas.
        ///Você está no caminho certo!.
        /// </summary>
        internal static string Sobrepeso {
            get {
                return ResourceManager.GetString("Sobrepeso", resourceCulture);
            }
        }
    }
}
